name: Build Docker Image
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ASzc/change-string-case-action@v1
        id: repo
        with:
          string: ${{github.repository}}
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          registry: ghcr.io
          image: ${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }} 
